# Welcome to Jekyll!

# Website settings
title: "KinglyJn"
description: "Kingly's blog,use Jekyll and github pages."
keywords: "kinglyjn,张庆力的博客,kinglyjn blog,kingly,Jekyll,github,gh-pages"
baseurl: "/"
url: "https://kinglyjn.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'KinglyJn'
  profile: 'http://www.hellozs.cn/studio/'
  first_name: 'Kingly'
  last_name: 'Jn'
  email: 'admin@datactr.cn'
  github_username: 'Kinglyjn'
  head_img: 'static/img/landing/Kinglyjn.png'
  desc: 'A Lazy Man, busy in selecting * from t_woman where (age between 20 and 30) and (married=false) and (feature is fashion dignified) and (bodyMind is healthy), gentle and caring disposition is better, do not bother if you are not pure-hearted ...'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States5.png'
  - locale: 'zh'
    flag: 'static/img/flags/China5.png'

# blog img path
img_path: 'http://dl.iteye.com/upload/picture/pic/'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

#share
socialShare:
  demo: 'http://overtrue.me/share.js/'

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
